-- Script de inicialización de Base de Datos para Supabase (PostgreSQL)
-- Generado para: Presupuesto Servitel
-- Este script crea las tablas, tipos (enums) e índices necesarios.

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. ENUMS (Tipos de datos personalizados)
DO $$ BEGIN
    CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'COMPANY_ADMIN', 'OPERATOR', 'AUDITOR', 'VIEWER');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "BudgetPeriodType" AS ENUM ('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "BudgetStatus" AS ENUM ('DRAFT', 'ACTIVE', 'CLOSED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "InvoiceStatus" AS ENUM ('REGISTERED', 'CANCELLED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "AlertType" AS ENUM ('BUDGET_EXCEEDED', 'ADJUSTMENT_MADE', 'SYSTEM_WARNING');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "CategoryType" AS ENUM ('EXPENSE', 'INCOME');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 3. TABLAS

-- Grupos Empresariales (Matrices)
CREATE TABLE IF NOT EXISTS "BusinessGroup" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Empresas
CREATE TABLE IF NOT EXISTS "Company" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "groupId" BIGINT REFERENCES "BusinessGroup"("id") ON DELETE SET NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Sucursales
CREATE TABLE IF NOT EXISTS "Branch" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "companyId" BIGINT NOT NULL REFERENCES "Company"("id") ON DELETE CASCADE,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Usuarios
CREATE TABLE IF NOT EXISTS "User" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "authId" UUID UNIQUE, -- ID devuelto por Supabase Auth (auth.users)
    "email" TEXT UNIQUE NOT NULL,
    "passwordHash" TEXT,
    "name" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'OPERATOR',
    "companyId" BIGINT REFERENCES "Company"("id") ON DELETE SET NULL,
    "branchId" BIGINT REFERENCES "Branch"("id") ON DELETE SET NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Categorías
CREATE TABLE IF NOT EXISTS "Category" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "companyId" BIGINT REFERENCES "Company"("id") ON DELETE CASCADE,
    "type" "CategoryType" NOT NULL DEFAULT 'EXPENSE',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE("name", "companyId", "type")
);

-- Subcategorías
CREATE TABLE IF NOT EXISTS "Subcategory" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "categoryId" BIGINT NOT NULL REFERENCES "Category"("id") ON DELETE CASCADE,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE("name", "categoryId")
);

-- Presupuestos (Maestros)
CREATE TABLE IF NOT EXISTS "Budget" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "type" "BudgetPeriodType" NOT NULL DEFAULT 'MONTHLY',
    "initialDate" TIMESTAMPTZ NOT NULL,
    "endDate" TIMESTAMPTZ NOT NULL,
    "amountLimitUSD" DECIMAL(19,4) NOT NULL,
    "status" "BudgetStatus" NOT NULL DEFAULT 'ACTIVE',
    "companyId" BIGINT NOT NULL REFERENCES "Company"("id") ON DELETE CASCADE,
    "branchId" BIGINT NOT NULL REFERENCES "Branch"("id") ON DELETE CASCADE,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Alocaciones de Presupuesto (Detalle por categoría)
CREATE TABLE IF NOT EXISTS "BudgetAllocation" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "budgetId" BIGINT NOT NULL REFERENCES "Budget"("id") ON DELETE CASCADE,
    "categoryId" BIGINT NOT NULL REFERENCES "Category"("id"),
    "subcategoryId" BIGINT REFERENCES "Subcategory"("id"),
    "amountUSD" DECIMAL(19,4) NOT NULL,
    "amountVES" DECIMAL(19,4) NOT NULL DEFAULT 0,
    "consumedUSD" DECIMAL(19,4) NOT NULL DEFAULT 0,
    "consumedVES" DECIMAL(19,4) NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE("budgetId", "categoryId", "subcategoryId")
);

-- Ajustes de Presupuesto
CREATE TABLE IF NOT EXISTS "BudgetAdjustment" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "allocationId" BIGINT NOT NULL REFERENCES "BudgetAllocation"("id") ON DELETE CASCADE,
    "reason" TEXT NOT NULL,
    "amountUSD" DECIMAL(19,4) NOT NULL,
    "amountVES" DECIMAL(19,4) NOT NULL DEFAULT 0,
    "recordedById" BIGINT NOT NULL REFERENCES "User"("id"),
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tasas de Cambio
CREATE TABLE IF NOT EXISTS "ExchangeRate" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "date" DATE UNIQUE NOT NULL,
    "usd" DECIMAL(19,4) NOT NULL,
    "eur" DECIMAL(19,4) NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Facturas
CREATE TABLE IF NOT EXISTS "Invoice" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "number" TEXT NOT NULL,
    "supplierName" TEXT NOT NULL,
    "allocationId" BIGINT NOT NULL REFERENCES "BudgetAllocation"("id") ON DELETE RESTRICT,
    "amountUSD" DECIMAL(19,4) NOT NULL,
    "amountVES" DECIMAL(19,4) NOT NULL,
    "exchangeRate" DECIMAL(19,4) NOT NULL,
    "date" TIMESTAMPTZ NOT NULL,
    "companyId" BIGINT NOT NULL REFERENCES "Company"("id") ON DELETE CASCADE,
    "registeredById" BIGINT NOT NULL REFERENCES "User"("id"),
    "status" "InvoiceStatus" NOT NULL DEFAULT 'REGISTERED',
    "attachmentKey" TEXT,
    "attachmentName" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Ingresos
CREATE TABLE IF NOT EXISTS "Income" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "number" TEXT NOT NULL,
    "clientName" TEXT NOT NULL,
    "categoryId" BIGINT NOT NULL REFERENCES "Category"("id") ON DELETE RESTRICT,
    "subcategoryId" BIGINT REFERENCES "Subcategory"("id") ON DELETE SET NULL,
    "amountUSD" DECIMAL(19,4) NOT NULL,
    "amountVES" DECIMAL(19,4) NOT NULL,
    "exchangeRate" DECIMAL(19,4) NOT NULL,
    "date" TIMESTAMPTZ NOT NULL,
    "companyId" BIGINT NOT NULL REFERENCES "Company"("id") ON DELETE CASCADE,
    "branchId" BIGINT REFERENCES "Branch"("id") ON DELETE SET NULL,
    "registeredById" BIGINT NOT NULL REFERENCES "User"("id"),
    "notes" TEXT,
    "attachmentKey" TEXT,
    "attachmentName" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Auditoría
CREATE TABLE IF NOT EXISTS "AuditLog" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "companyId" BIGINT REFERENCES "Company"("id") ON DELETE CASCADE,
    "userId" BIGINT REFERENCES "User"("id"),
    "action" TEXT NOT NULL,
    "entity" TEXT NOT NULL,
    "entityId" TEXT NOT NULL, -- Mantenemos TEXT por si se hace auditoría de Auth u otros IDs que sean de texto/UUID fuera de la app
    "details" JSONB,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Alertas
CREATE TABLE IF NOT EXISTS "Alert" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "companyId" BIGINT NOT NULL REFERENCES "Company"("id") ON DELETE CASCADE,
    "type" "AlertType" NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "isRead" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. ÍNDICES
CREATE INDEX IF NOT EXISTS idx_budget_company_dates ON "Budget" ("companyId", "initialDate", "endDate");
CREATE INDEX IF NOT EXISTS idx_invoice_company_date ON "Invoice" ("companyId", "date");
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON "AuditLog" ("companyId", "createdAt");
CREATE INDEX IF NOT EXISTS idx_branch_company ON "Branch" ("companyId");
CREATE INDEX IF NOT EXISTS idx_user_company ON "User" ("companyId");
CREATE INDEX IF NOT EXISTS idx_exrate_date ON "ExchangeRate" ("date");

-- 5. SEGURIDAD (Habilitar RLS)
ALTER TABLE "BusinessGroup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Company" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Branch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Subcategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Budget" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BudgetAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BudgetAdjustment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExchangeRate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Income" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Alert" ENABLE ROW LEVEL SECURITY;

-- 6. RPC / FUNCIONES
CREATE OR REPLACE FUNCTION adjust_allocation_on_invoice(
    p_allocation_id BIGINT,
    p_amount_usd DECIMAL,
    p_amount_ves DECIMAL
)
RETURNS VOID AS $$
BEGIN
    UPDATE "BudgetAllocation"
    SET "consumedUSD" = "consumedUSD" + p_amount_usd,
        "consumedVES" = "consumedVES" + p_amount_ves,
        "updatedAt" = now()
    WHERE id = p_allocation_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_my_profile()
RETURNS TABLE (
    user_branch_id BIGINT,
    user_company_id BIGINT,
    user_role "Role"
) AS $$
BEGIN
    RETURN QUERY
    SELECT "branchId", "companyId", role
    FROM "User"
    WHERE "authId" = auth.uid()
    LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

